### ISSUE TITLE
Add IPTV Manager support

### ISSUE THREAD

**Issue by dagwieers** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#400] opened 2021-01-12 13:13 UTC
**Describe the solution you'd like**
As a Catch-up TV & More user as well as an IPTV Manager user, I was hoping that Catch-up TV & More could support IPTV Manager. I noticed the pop-up recently advertising: https://catch-up-tv-and-more.github.io/live_tv_installation/

But there is an easier and standardized way to get your Live TV and VOD content into Kodi's TV/Radio sections without "hijacking" PVR IPTV Simple.

IPTV Manager can scan add-ons that support it, and request updates about Live channels and EPG directly to your add-on and update PVR IPTV Simple. This works across add-ons and asynchronously, and does not require anything advanced.

**Additional context**
You can find more information about IPTV Manager from:
- https://github.com/add-ons/service.iptv.manager/wiki

We have an Add-ons Slack channel were we unite add-on developers, if you send me your email-address privately we can add you and help with the integration if needed.

**Comment by sy6sy2** [comment] 2021-01-12 18:23
Wow! I discover this add-on with your message and after a fast read I can confirm that IPTV Manager should be a really good solution instead of our IPTV Simple hack 😛

I am not able to do it at the moment because of a new job and my thesis to finish but maybe @wwark want to have a look?
If not, I will do it later 😉 

Thank you for contacting us about that!

**Comment by wwark** [comment] 2021-01-15 12:12
Hi,
I will take a look this Week-End !

**Comment by dagwieers** [comment] 2021-01-15 12:48
@sy6sy2 @wwark We have a Slack for add-on developers where we can interact. I can add you if you mail me your email address. We are very interested in feedback on how to improve IPTV Manager, or the documentation.

**Comment by wwark** [comment] 2021-01-18 19:27
I installed IPTV Manager and read the wiki pages.
So if I understand correctly after integration of IPTV Manager we don't need to provide those steps https://catch-up-tv-and-more.github.io/live_tv_installation/
It will be automatically configured for the end user. Am I right ?

**Comment by dagwieers** [comment] 2021-01-18 22:27
The user will need to run the IPTV Manager configuration once. See the **Set up IPTV Simple** section in the installation.
https://github.com/add-ons/service.iptv.manager/wiki/Installation

**Comment by dagwieers** [comment] 2021-01-26 16:21
So I was looking into this today, and what would probably be the easiest is to only expose the Live TV channels that have been added as a add-on favorite to the Kodi Channels list. This would allow the user to select exactly which channels they would like to appear in the TV sections.

Why? Because in my use-case I am interested in a handful of channels from Catch-up TV & More:
- Eén (BE/NL)
- Canvas (BE/NL)
- Ketnet (BE/NL)
- NPO Nieuws (NL)
- NPO Politiek (NL)
- CBS News (US)
- ABC News (US)
- BVN (International)

So that means 2 US channels, 1 International channel, 2 NL channels and 3 Belgian/Flemish channels. Exposing all channels would be too much, but even enabling per country would in my case expose too many channels I am not interested in.

**Comment by sy6sy2** [comment] 2021-01-30 07:44
Hi @dagwieers,
I am looking at IPTV Manager this morning and I found this "system" really good.

If I understand correctly IPTVManager will create one specific Channels group for each supported video add-on that expose channels to IPTV Manager.
So, as you said, our users needs to select each channel of Catch-Up Tv & More they want to have in the Live TV section of Kodi.
I understand your idea concerning our Favorites folder that IPTV Manager may use to grab channels, but if possible I would like to keep things separate. So my idea is to have a "Choose channels" button in the settings where the user will be able to choose which channel he want to have in Live TV section of Kodi. We can imagine two sub-buttons: The first one to add an full country folder (let's say the user simple one to select all French Live TV channels), and, in addition, another button where the user can select individually more channels (let's say the user also want to add some French Canadian and Belgium channels).
What do you think @wwark and @dagwieers?

Also, I have another question: While IPTVManager grab new data from each supported add-ons, is IPTVManager use some kind of timeout to abort a too long addon refresh?

Thank you!

**Comment by dagwieers** [comment] 2021-01-30 11:15
> If I understand correctly IPTVManager will create one specific Channels group for each supported video add-on that expose channels to IPTV Manager.

Not necessarily. If you do not provide a group-entry per channel, it will put everything in the same channel group. But you can override this. Our aim in designing the JSON-STREAMS format is to have a 1:1 mapping with M3U8 (from a Kodi perspective).

> if possible I would like to keep things separate

I agree, I don't think the add-on favourites are reusable for the IPTV channel lists. (It lacks a lot of the metadata, and the name is modified).

> So my idea is to have a "Choose channels" button in the settings where the user will be able to choose which channel he want to have in Live TV section of Kodi. We can imagine two sub-buttons: The first one to add a full country folder (let's say the user simply want to select all French Live TV channels), and, in addition, another button where the user can select individually more channels (let's say the user also want to add some French Canadian and Belgium channels).

Personally, I would not make it too complex and would only provide a selection window to enable/disable channels. (default = disabled). Having lots of channels in the TV section is not necessarily beneficial, not even per country (there are channels you would never look at anyway). My preferred interface would have been `xbmcgui multiselect` from the settings.

> Also, I have another question: While IPTVManager grab new data from each supported add-ons, is IPTVManager use some kind of timeout to abort a too long addon refresh?

An add-on has 10 seconds to open the returning socket. At the moment there is no timeout once the socket connection has been opened. We have some guidelines on how the add-on must behave, e.g. open the connection immediately and then compile the data. But it is possible in the future we may also add a timeout for when the socket was opened and no data was returned within X seconds.

When more add-ons support IPTV Manager, we may have a more advanced scheme here too, and have X parallel add-on queries to speed up refreshing. And we hope at some point to offer HTTP as an alternative to socket-based communication, in this case we could allow for asynchronous updates too. (We have some ideas around it, but not everything is agreed upon)

**Comment by sy6sy2** [comment] 2021-01-30 11:24
Thank you for your complete answer.
I will try this ASAP on a new branch 😉

**Comment by dagwieers** [comment] 2021-01-30 12:36
Can't wait to try this and help out. We have a Slack channel and an Add-ons GitHub organization for Kodi developers to discuss internals and best practices. Send me a PM if you want to join.

**Comment by sy6sy2** [comment] 2021-02-01 13:31
Hi guys,
The initial support of IPTV Manager is here https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/tree/iptv_manager if you want to try.

By default IPTV Manager is disabled. You need to enable it from the plugin settings and also select each channels that you want to see in Kodi Live TV.

I still need to implement EPG support and also channels with multiples languages like Arte.

Feel free to try and tell me for any idea, bug are change 😉  Thanks.

**Comment by dagwieers** [comment] 2021-02-01 23:39
@sy6sy2 It works pretty well! The only suggestion I have is to sort the channels in the multiselect window so it is easier to find something specific. But that is it. I am looking forward to try out the EPG support as well. Thanks for the nice collaboration 👍🏻

**Comment by wwark** [comment] 2021-02-07 08:36
IPTV Manager is added to CUTV&More.
Thanks @dagwieers to propose it.
I close this ticket !

**Closed by wwark** 2021-02-07 08:36 UTC
Labels: Type: Enhancement, Type: New feature
