### ISSUE TITLE
correct versioning of resource.images.catchuptvandmore

### ISSUE THREAD

**Issue by darodi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#680] opened 2022-03-08 18:36 UTC
### Describe the bug
correct versioning of resource.images.catchuptvandmore
new images have been added in beta version

- [x] https://github.com/Catch-up-TV-and-More/resource.images.catchuptvandmore version should be incremented to 1.0.13
- [x] in [plugin.video.catchuptvandmore](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore) :    addon.xml
      `<import addon="resource.images.catchuptvandmore" version="1.0.13"/>`
- [x] update https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore  with new zips and so on

**Comment by joaopa00** [comment] 2022-03-09 07:30
Thanks Darodi for the remainder. I did what you requested in the first two items. The last one is automatic, following to what I understood. I hope everything is fine.

**Comment by darodi** [comment] 2022-03-09 22:44
last one is not created from 
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/dev/.github/workflows/release.yml
and 
https://github.com/Catch-up-TV-and-More/resource.images.catchuptvandmore/blob/master/.github/workflows/ci.yml
?


I still can't see v1.0.13 here:
https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore/tree/master/zips/krypton_beta/resource.images.catchuptvandmore

**Comment by joaopa00** [comment] 2022-03-10 01:53
Umm... It looks like the problem is here only for the beta repo. Strange!

**Comment by joaopa00** [comment] 2022-03-10 06:10
Should be fixed in current git. I saw the 0.13 version in repo.

**Closed** 2022-03-10 07:09 UTC
