### ISSUE TITLE
Channel settings list scrolling issue

### ISSUE THREAD

**Issue by Forage** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#90] opened 2018-10-06 11:04 UTC
When scrolling through the list of channels in the settings some channels are not accessible.
With all settings reset to default:
- If you scroll down in the list, it will not go further than the "International" channel "NHK World"
- If you scroll up, causing it to restart at the end of the list, it will jump to the "Cancel" button after the "International" channel "TV5Monde France Belgique Suisse" before jumping to "Afrique Media"
- If you continue going up it will not go further than the "International" channel "Bein Sports"

I tried removing the whole section of channels in the XML file, but this makes the scrolling issue simply occur elsewhere.
I do not see anything wrong in the XML structure or values either.

What could be the problem here?

**Comment by wwark** [comment] 2018-10-06 11:40
Hi Forage,
You are in Kodi 18?
Last time I check on Kodi 17 we don't have the issue.
I think it is a problem in Kodi 18 and menu with too many datas ... the website part don't have the issue for the moment.
Kodi 18 is still under development.
I will fill an issue on kodi track for that.
Thanks,

**Comment by Forage** [comment] 2018-10-06 11:48
Yeah, Kodi 18b3

**Comment by SylvainCecchetto** [comment] 2018-10-11 20:42
I can confirm that I have the same bug with Kodi 18b3 and the code quick branch of the add-on.
The scrolling seems buggy with some lag for me.
I'm on a mac.

Seems to be a Kodi issue, we will see with next beta ;-)

**Comment by Forage** [comment] 2018-10-26 07:47
The issue remains in kodi beta4, with the codequick version of the plu add-on as well.
@wwark did you file a bug for this in the Kodi tracker?

**Comment by wwark** [comment] 2018-10-26 08:43
Hi Forage,
Not for the moment. I will do it.
Thank you,

**Comment by wwark** [comment] 2018-10-26 09:05
Opened https://github.com/xbmc/xbmc/issues/14721

**Comment by SylvainCecchetto** [comment] 2020-01-28 17:32
Fixed by https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/eb4a6bb381645d67b0b5059dde8a9d554b4ecc5a
Will be available v0.2.17

**Closed by SylvainCecchetto** 2020-01-28 17:32 UTC
Labels: bug, kodi 18
