### ISSUE TITLE
Playback failed error message in Kodi 17.6!

### ISSUE THREAD

**Issue by funtravel1208** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#51] opened 2018-03-25 01:55 UTC
Hello,
I am experiencing some issues with Catch Up TV for some TV shows. I cannot figure out what is the issue. It's very random and does not happen consistently.
The error message is "Playback failed: one or more items failed to play. Check log for more information"
Any idea how I could fix this??

Thanks!

**Comment by wwark** [comment] 2018-04-09 02:08
Hello Christine,

I don't see any attached file. Could you please attach again ?
Which version of plugin do you use ? We fixed something in the last developemment version 0.1.11~beta16?
Could you please try with this version ?

Thanks,
Wwark

**Comment by funtravel1208** [comment] 2018-04-09 23:59
Hi Marc,

Looks like I have the 0.1.11beta17!
Also, I noticed that the information TV shows in Replay from France 2 are not updated anymore.... :( The latest « JT 20h » is from 04/04/2018...


Christine

**Comment by wwark** [comment] 2018-04-10 04:55
Hi Christine,

It is possible if the FranceTV don't update the api we used. It arrives sometimes i think.
We can't do anything for that. If the API is not used anymore we have to change to get a new one with regular update ...

Wwark.

**Comment by funtravel1208** [comment] 2018-04-10 23:50
Hi Marc,

This is very odd! I usually watch the news “JT 20h”  in Replay on France 2 and it was updated everyday, and then it stopped on 04/04/18... However, other shows that I watch everyday from France 2 too, are updated as usual. Can it be due to the API too??? Does the API involve all updates or is it specific to shows???

Thanks!

Christine

**Comment by wwark** [comment] 2018-04-11 09:45
Yes I know ...
But we used the same code (call) to get every shows etc ...
We don't have any specific code for JT 20H so the problem is on the side in FranceTV i guess ...

**Comment by funtravel1208** [comment] 2018-04-12 11:09
Hi Marc,

This is too bad. I was amazed by the speed at which the replay videos were available but now it’s over... :( The folder of JT 20h has disappeared now... 
However, I am still confused. Their replays are available on their website. Are you sure there is nothing you can do????

Thanks!!!!

Christine

**Comment by wwark** [comment] 2018-04-12 13:07
Hi Christine,
We have to take a look if we have to change the API.

Nevertheless, the JTs are available in the replay of France Info in the last version of developement of the plugin.

Regards,
Wwark

**Comment by wwark** [comment] 2018-04-12 14:18
We plan to change the API - Work TODO

**Comment by funtravel1208** [comment] 2018-04-12 14:41
That would be awesome!  Thanks so much!!!!

Christine

**Comment by wwark** [comment] 2018-04-13 14:55
Can you test ?
Thanks,
Wwark

**Comment by funtravel1208** [comment] 2018-04-13 15:37
Sure! I will test when I get back home tonight!

Thanks so much for working on this! I appreciate it !!!!

Christine

**Comment by funtravel1208** [comment] 2018-04-14 14:35
Hi Marc!!!

OMG! What you did is AWESOME!!!! Yes, it’s working!!! I like a lot how it’s organized!!!!!

Thanks so much!!!!

Christine

**Comment by wwark** [comment] 2018-04-14 22:57
Good I will close this ticket :)

Thanks,
Wwark

**Closed by wwark** 2018-04-14 22:57 UTC
Labels: enhancement
