### ISSUE TITLE
Settings not available

### ISSUE THREAD

**Issue by marcteyssier** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#401] opened 2021-01-15 11:48 UTC
Hi,

I have install the Catchup Tv version matrix 0.2.27 but when I want to configure it, the parameters list is empty.

I don't know why.
![20210115_124914](https://user-images.githubusercontent.com/2227717/104723663-e4e19300-572f-11eb-832a-912308dac2d6.jpg)

Regards

**Comment by wwark** [comment] 2021-01-15 12:12
Hi,
You are not the only one with this issue.
It is link to the settings.xml produced and used by the plugin ... this file is maybe altered.
The test will be to remove it.

~/.kodi/userdata/addon_data/plugin.video.catchuptvandmore$ ls -l
total 144
-rw-rw-r-- 1 wark wark     0 janv. 15 12:59 cache_check
-rw-rw-r-- 1 wark wark    45 août  10 08:19 favourites.json
-rw-rw-r-- 1 wark wark   155 juin  21  2020 menus_settings.json
-rw-rw-r-- 1 wark wark   221 sept. 10 19:21 _new_searches.pickle
**-rw-rw-r-- 1 wark wark 46517 juin  21  2020 settings.xml**
-rw-r--r-- 1 wark wark 86016 août  17 21:53 _youtube-cache.sqlite

The directory userdata location depends of the OS (https://kodi.wiki/view/Userdata#Location)

Thanks,

**Comment by sy6sy2** [comment] 2021-01-24 18:17
Hi, which OS/hardware?

**Comment by wwark** [comment] 2021-02-27 15:39
@marcteyssier Is the issue is still present on your side ?

**Comment by wwark** [comment] 2021-03-06 09:53
I close this ticket.
You can reopen again if needed.
Thanks.

**Closed by wwark** 2021-03-06 09:53 UTC
