### ISSUE TITLE
Error while updating Widevine CDM

### ISSUE THREAD

**Issue by SansanLaTulipe** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#763] opened 2022-04-11 23:56 UTC
### Describe the bug

While updating Widevine CDM, an error occurs after the end of download.

### To Reproduce

Steps to reproduce the behaviour:
1. Install the addon
2. Browse to a video replay (in my case, France > myCANAL > C8)
3. Play
4. Accept Widevine CDM update (2-3 pop-ups)

### Expected behaviour

Installation success and video play.

### Actual behaviour

During the update process, a pop-up appears with an "unexpected" error (sharing the error logs failed as well).

### Your environment

 - Raspberry-Pi
 - Operating system version/name: Raspberry-Pi OS lite (bullseye, upgraded from buster)
 - Kodi version: 19.4
 - Catch-up TV & More version: 0.2.37
 - Installation method: from ZIP file ([plugin.video.catchuptvandmore-no-openvpn.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/releases/download/v0.2.37/plugin.video.catchuptvandmore-no-openvpn.zip))

### Debug log
```
2022-04-12 01:25:05.439 T:1749    ERROR <general>: CPVRTimerInfoTag: No epg tag given for epg based timer type (3)!
2022-04-12 01:25:06.456 T:4851    FATAL <general>: Skipped 19 duplicate messages..
2022-04-12 01:25:06.456 T:4851    FATAL <general>: [script.module.inputstreamhelper] File libwidevinecdm.so not found in the ChromeOS image
2022-04-12 01:25:06.458 T:4851    FATAL <general>: [script.module.inputstreamhelper] Extracting widevine from the zip failed!
2022-04-12 01:25:07.008 T:1749    ERROR <general>: CPVRTimerInfoTag: No epg tag given for epg based timer type (3)!
2022-04-12 01:25:07.666 T:4851    ERROR <general>: Skipped 9 duplicate messages..
2022-04-12 01:25:07.666 T:4851    ERROR <general>: [Catch-up-TV-&-More.support] HTTPSConnectionPool(host='secure-gen-hapi.canal-plus.com', port=443): Max retries exceeded with url: /conso/playset/unit/18496342_50013 (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)')))
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 699, in urlopen
                                                       httplib_response = self._make_request(
                                                     File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 382, in _make_request
                                                       self._validate_conn(conn)
                                                     File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 1010, in _validate_conn
                                                       conn.connect()
                                                     File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 411, in connect
                                                       self.sock = ssl_wrap_socket(
                                                     File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
                                                       ssl_sock = _ssl_wrap_socket_impl(
                                                     File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
                                                       return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
                                                     File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
                                                       return self.sslsocket_class._create(
                                                     File "/usr/lib/python3.9/ssl.py", line 1040, in _create
                                                       self.do_handshake()
                                                     File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
                                                       self._sslobj.do_handshake()
                                                   ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 439, in send
                                                       resp = conn.urlopen(
                                                     File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 755, in urlopen
                                                       retries = retries.increment(
                                                     File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 574, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='secure-gen-hapi.canal-plus.com', port=443): Max retries exceeded with url: /conso/playset/unit/18496342_50013 (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)')))

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/home/kodi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/mycanal.py", line 455, in get_video_url
                                                       value_datas_json = session_requests.get(URL_VIDEO_DATAS % video_id, headers=headers)
                                                     File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 555, in get
                                                       return self.request('GET', url, **kwargs)
                                                     File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 542, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 655, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 514, in send
                                                       raise SSLError(e, request=request)
                                                   requests.exceptions.SSLError: HTTPSConnectionPool(host='secure-gen-hapi.canal-plus.com', port=443): Max retries exceeded with url: /conso/playset/unit/18496342_50013 (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)')))
2022-04-12 01:25:07.694 T:4851  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
```

**Comment by Arias800** [comment] 2022-04-12 06:21
`Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)')))`
The ssl error is fixed on the current beta.

```
2022-04-12 01:25:06.456 T:4851    FATAL <general>: [script.module.inputstreamhelper] File libwidevinecdm.so not found in the ChromeOS image
2022-04-12 01:25:06.458 T:4851    FATAL <general>: [script.module.inputstreamhelper] Extracting widevine from the zip failed!
```
This isn't an issue of CaptchTv and more.
https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/511

**Comment by joaopa00** [comment] 2022-04-12 16:50
Closing then...

**Closed by joaopa00** 2022-04-12 16:50 UTC

**Comment by sansanlatulipe** [comment] 2022-04-12 21:14
Thanks for your quick answer :-)
