### ISSUE TITLE
IPTV Manager Error

### ISSUE THREAD

**Issue by GaetanBaert** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#592] opened 2021-12-19 18:24 UTC
### Describe the bug
When trying to install live TV integration, it triggers some errors : "unable to import route module : 'resources.lib.iptvmanager'.

### To Reproduce
1.Install catch-up TV & more
2.Install IPTV manager from TV integration

### Your environment
 - [ x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19.3
 - Catch-up TV & More version: 0.2.36
 - Installation method: from the stable branch of the repo

**Comment by wouaco** [comment] 2021-12-19 20:33
Hi, same problem for me

**Comment by fireced** [comment] 2021-12-19 21:13
Same problem for me too!

**Comment by alexbelgium** [comment] 2021-12-19 21:25
Same

**Comment by jlb312** [comment] 2021-12-19 23:07
Same

**Comment by QGJ37** [comment] 2021-12-20 08:19
Same problem here since yesterday on a Firestick TV.

**Comment by Ricounnet** [comment] 2021-12-20 09:09
Same here on a miBox.

Logs:
```
2021-12-19 18:30:31.906 T:9414    ERROR <general>: [Catch-up-TV-&-More.support] 'unable to import route module: resources.lib.iptvmanager'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 248, in get
_route
                                                       importlib.import_module(module_path)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
                                                       return _bootstrap._gcd_import(name[level:], package, level)
                                                     File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 783, in exec_module
                                                     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/iptvmanager.py", line 1
7, in <module>
                                                       from resources.lib.xmltv import grab_programmes
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/xmltv.py", line 32, in
<module>
                                                       from tzlocal import get_localzone
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.tzlocal/lib/tzlocal/__init__.py", line 5, in <module>

                                                       from tzlocal.unix import get_localzone, reload_localzone
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.tzlocal/lib/tzlocal/unix.py", line 12, in <module>
                                                       from backports.zoneinfo import ZoneInfo, ZoneInfoNotFoundError
                                                   ModuleNotFoundError: No module named 'backports'

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 300, in run
_callback
                                                       route = self.get_route(self.selector)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 250, in get
_route
                                                       raise RouteMissing("unable to import route module: %s" % module_path)
                                                   codequick.support.RouteMissing: 'unable to import route module: resources.lib.iptvmanager'
2021-12-19 18:30:31.990 T:9414  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-12-19 18:30:39.236 T:9410    ERROR <general>: [service.iptv.manager] [resources.lib.modules.addon] Something went wrong while calling plugin.video.catchuptvandmore: Timout waiting for rep
ly on port 42539

```

**Comment by Ykwily** [comment] 2021-12-20 16:47
Same problem on new install and problem with actuel installation on raspberry pi 4 : 2021-12-19 23:06:57.750 T:3624    ERROR <general>: [Catch-up-TV-&-More.support] 'unable to import route module: resources.lib.iptvmanager'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 248, in get_route
                                                       importlib.import_module(module_path)
                                                     File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
                                                     File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 783, in exec_module
                                                     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/iptvmanager.py", line 17, in <module>
                                                       from resources.lib.xmltv import grab_programmes
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/xmltv.py", line 32, in <module>
                                                       from tzlocal import get_localzone
                                                     File "/storage/.kodi/addons/script.module.tzlocal/lib/tzlocal/__init__.py", line 5, in <module>
                                                       from tzlocal.unix import get_localzone, reload_localzone
                                                     File "/storage/.kodi/addons/script.module.tzlocal/lib/tzlocal/unix.py", line 12, in <module>
                                                       from backports.zoneinfo import ZoneInfo, ZoneInfoNotFoundError
                                                   ModuleNotFoundError: No module named 'backports'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 300, in run_callback
                                                       route = self.get_route(self.selector)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 250, in get_route
                                                       raise RouteMissing("unable to import route module: %s" % module_path)
                                                   codequick.support.RouteMissing: 'unable to import route module: resources.lib.iptvmanager'

**Comment by staffly** [comment] 2021-12-20 17:50
Problem started with last osmc update (Kodi 19.3 see https://osmc.tv/2021/11/osmcs-november-update-is-here-with-kodi-19-3/)
log available here : https://paste.osmc.tv/haxuwokovu (from command line : `grab-logs -A`)

**Comment by emnbdx** [comment] 2021-12-20 20:08
I have the same problem on osmc, and I found a work around.

When I look to your logs I see that

```
File "/storage/.kodi/addons/script.module.tzlocal/lib/tzlocal/unix.py", line 12, in <module>
from backports.zoneinfo import ZoneInfo, ZoneInfoNotFoundError
ModuleNotFoundError: No module named 'backports'
```

So I try to add missing module and everything work.
Module is this one : https://pypi.org/project/backports.zoneinfo

And command I play

```
cd .kodi/addons/script.module.tzlocal/lib
wget https://files.pythonhosted.org/packages/ad/85/475e514c3140937cf435954f78dedea1861aeab7662d11de232bdaa90655/backports.zoneinfo-0.2.1.tar.gz
tar -xzvf backports.zoneinfo-0.2.1.tar.gz 
mv backports.zoneinfo-0.2.1/src/backports .
rm -r backports.zoneinfo-0.2.1.tar.gz backports.zoneinfo-0.2.1
```

Have fun ;)

**Comment by alexbelgium** [comment] 2021-12-20 20:15
Confirmed working. You're the best.

**Comment by QGJ37** [comment] 2021-12-20 20:20
How do you install this missing module on an android device ?

**Comment by Ricounnet** [comment] 2021-12-20 20:54
> How do you install this missing module on an android device ?

I can connect ssh to an Android box but the wget doesn't work neither the curl.

I'm looking for a solution for the workaround. I hope a better solution will be found with an update. :-)

**Comment by jlb312** [comment] 2021-12-20 21:16
I confirm the workaround on librelelec 10.0.1 with RPI4.

SSH connection + pasting commands as @emnbdx did on osmc.

Many Thanks to @emnbdx

Any way it doesn't explain why this bug happened to day as everythings worked well yesterday on Libreelec without any update from my part.

JL

**Comment by YannBrrd** [comment] 2021-12-21 12:17
+1

'No module named backports'

**Comment by alexlehay** [comment] 2021-12-21 14:14
Guys, I'm using Kodi on a firestick and I have found a workaround on another website. 
To make it work, you have to deselect the TV guide in the Catch up extension parameters. My menu is in French sorry, so the parameter to deselect is "Activer le programme TV (plus lent)" located in the "Qualité et Contenu" section in the parameters. 

Then I'm able to watch the Live TV using the catch up TV extension. However m I can't use the TV module integrated in Kodi. 

I hope an official solution will be offered soon. Thanks for your hard work. 

Alexis

**Comment by darodi** [comment] 2021-12-21 23:21
an other workaround on osmc kodi 19.3
OSMC 2021.11-2

SSH connection + pasting 

```
sudo apt-get -y install python3-pip gcc-arm-linux-gnueabihf python3-dev
sudo pip3 install backports.zoneinfo
```

**Comment by wouaco** [comment] 2021-12-22 07:40
Workaround suggested by @alexlehay 2 replies above works well for me.

**Comment by sy6sy2** [comment] 2021-12-22 12:27
Hi all, thank you for this issue, the workaround and all the comments.
I was able to reproduce the issue and the issue seems to come from the recent update of the package `tzlocal` used by CUTV&M as a dependency (see https://github.com/xbmc/repo-scripts/pull/2122).

I will try to push a fix soon in order to bypass the usage of tzlocal in case of error.

**Comment by sy6sy2** [comment] 2021-12-22 12:35
I just pushed 0.2.37~beta07 version of the plugin to fix (temporary) this issue.
This fix will assume that your timezone is Paris in case the import of tzlocal failed.
This fix does not need the workaround suggested by @emnbdx (thank you guy for this fix!)

I will keep this issue open until the issue is fixed by the maintainer of tzlocal package.

**Comment by manuhbt** [comment] 2021-12-22 14:33
How can I get 0.2.37~beta07 version on an FireTV stick ?

**Comment by sy6sy2** [comment] 2021-12-22 14:34
You can follow this guide https://catch-up-tv-and-more.github.io/installation/ and use the beta channel

**Comment by fradav** [comment] 2021-12-22 15:05
> You can follow this guide https://catch-up-tv-and-more.github.io/installation/ and use the beta channel

The suggested repo there : https://catch-up-tv-and-more.github.io/repo
contains outdated plugins version for krypton. Is there another url ?

**Comment by william-diego** [comment] 2021-12-22 15:07
0.2.37~beta08 version is available and it works , thank you!

**Comment by manuhbt** [comment] 2021-12-22 16:21
0.2.37~beta08 version works fine for me as well, thank you!

**Comment by joaopa00** [comment] 2021-12-22 18:38
Au finial, c'est un bug dans Catchuptvmore ou dans tzlocal ?
Parce que de ce comrend du fix, si  l'appel à tzlocal échoue alors un fuseau horaire par défaut est posé. Mais l'appel à tzlocal ne devrait pas échouer normalement.
Si c'est n peu dans tzlocal, il serait bon qu'il soit reporté aux développeurs de cette bibliothèque.

**Comment by danwador** [comment] 2021-12-22 19:05
La version bêta fonctionne bien c est parfait

**Comment by Pauliakov** [comment] 2021-12-22 21:12
0.2.37~beta08 works perfectly !

**Comment by Phigen** [comment] 2021-12-27 17:47
Bonjour et merci.
Le plugin refonctionne, mais impossible d'avoir le LiveTV avec PVR.iptv.Simple.Client. Je pense que c'est en liaison avec IPTVManager.
Je suis sur Android.
Merci et bonne soirée.

**Comment by joaopa00** [comment] 2022-02-25 19:28
Timezone a été fixé par son développeur. Ce bug a été fixé upstream.

**Closed by joaopa00** 2022-02-25 19:28 UTC
Labels: Type: Bug, Kodi v19 - Matrix, Component: IPTV Manager
