### ISSUE TITLE
TV5 Unis

### ISSUE THREAD

**Issue by Europe57** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#800] opened 2022-04-27 15:57 UTC
### Describe the bug
A clear and concise description of what the bug is:

### To Reproduce
Steps to reproduce the behaviour:
1. TV5 Unis
2. Toute les catégories proposées

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead: KeyError 'url'

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19.4
 - Catch-up TV & More version: 0.2.38~beta25
 - Installation method: Reposity

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment] 2022-04-27 18:49
Duplicate of issue #483. Closing...

**Closed by joaopa00** 2022-04-27 18:49 UTC
