### ISSUE TITLE
France Télévision 404 HTTPerror

### ISSUE THREAD

**Issue by jun3d4y** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#567] opened 2021-10-07 09:28 UTC
### Describe the bug
A clear and concise description of what the bug is:
When trying to watch a France Télévision channel, I get a 404 http error.

### To Reproduce
1.Install kodi on rpi0
2.Install CatchUpTvAndMore (beta or not)
3.Launch a France Télévision channel
4.

### Expected behavior
A clear and concise description of what you expected to happen:
The channel to be played

### Actuel behavior
Tell us what happens instead:
404 HTTPerror

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 18.9
 - Catch-up TV & More version: 0.2.36 and 0.2.35
 - Installation method: offical kodi package and custom repo

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by sy6sy2** [comment] 2021-10-20 18:56
Duplicate of #558

**Closed by sy6sy2** 2021-10-20 18:56 UTC
