### ISSUE TITLE
Arte (F) and Tv5 Monde KO 

### ISSUE THREAD

**Issue by Rvhalewyn** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#462] opened 2021-03-06 15:47 UTC
### Describe the bug
A clear and concise description of what the bug is:
Arte and France 5 Monde do not open, blank EPG 

### To Reproduce
1.Open Guide
2.Click Arte or Tv5 Monde 
3.
4.

### Expected behavior
A clear and concise description of what you expected to happen:
Channel opens 
### Actuel behavior
Tell us what happens instead:
Channel hangs 
### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - LIBREELEC 9.2.5 

 - Operating system version/name:
 - Kodi version: 18.9
 - Catch-up TV & More version: 0.2.32 
 - Installation method: Kodi Repository 

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by wwark** [comment] 2021-03-06 16:13
Hi,
Could you please provide debug log of Kodi for both cases ?
The contents can be geo-localized so it is better you have access to the content with a web browser on the website in the same network of your kodi instance.

Thanks,

**Comment by enigma131** [comment] 2021-03-06 17:36
I can't reproduce. Arte live and TV5 are working .. but kodi 19 everywhere now...

**Comment by Rvhalewyn** [comment] 2021-03-06 18:04
Thanks.
Kodi 19 not possible on LIBRELEC yet.
I'll send you a debug tomorrow or Monday. 

Kind regards
Rudy Vanhalewyn 
Winston Churchilllaan 23 bus 14 
B-8300 Knokke-Heist 
BELGIUM 



-------- Origineel bericht --------
Van: enigma131 <notifications@github.com>
Verzonden: 6 maart 2021 18:37:07 CET
Aan: "Catch-up-TV-and-More/plugin.video.catchuptvandmore" <plugin.video.catchuptvandmore@noreply.github.com>
CC: Rvhalewyn <Rudy.Vanhalewyn@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Arte (F) and Tv5 Monde KO  (#462)

I can't reproduce. Arte live and TV5 are working .. but kodi 19 everywhere now...

**Comment by Rvhalewyn** [comment] 2021-03-08 15:00
For at little as I know about debugging, the results for arte should be here
paste.kodi.tv/suhogurizo

Kind regards
Rudy Vanhalewyn 
Winston Churchilllaan 23 bus 14 
B-8300 Knokke-Heist 
BELGIUM 



-------- Origineel bericht --------
Van: enigma131 <notifications@github.com>
Verzonden: 6 maart 2021 18:37:07 CET
Aan: "Catch-up-TV-and-More/plugin.video.catchuptvandmore" <plugin.video.catchuptvandmore@noreply.github.com>
CC: Rvhalewyn <Rudy.Vanhalewyn@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Arte (F) and Tv5 Monde KO  (#462)

I can't reproduce. Arte live and TV5 are working .. but kodi 19 everywhere now...

**Comment by wwark** [comment] 2021-03-08 15:26
Hi,
The error is we don't find any contents to play.
Like said before, those contents can be geo-localized.
Where do you live ? Are you able to play Arte Live TV on their website ?
Thanks,

**Comment by Rvhalewyn** [comment] 2021-03-08 15:42
I live in Belgium, so there should be no geoblocking issues for Arte or Tv5 Monde France Belgique Suisse.

Live works perfectly with my browser, on demand works also through your add-on. Only live isn't working on the add-on.

I also integrated your add-on with iptv Manager, all other channels work perfectly, even the French by using VPN.
In my iptv epg grid I see all information for your channels, except the same 2, Arte and TV France Monde. 

Kind regards
Rudy Vanhalewyn 
Winston Churchilllaan 23 bus 14 
B-8300 Knokke-Heist 
BELGIUM 



-------- Origineel bericht --------
Van: Marc Roy <notifications@github.com>
Verzonden: 8 maart 2021 16:27:05 CET
Aan: "Catch-up-TV-and-More/plugin.video.catchuptvandmore" <plugin.video.catchuptvandmore@noreply.github.com>
CC: Rvhalewyn <Rudy.Vanhalewyn@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Arte (F) and Tv5 Monde KO  (#462)

Hi,
The error is we don't find any contents to play.
Like said before, those contents can be geo-localized.
Where do you live ? Are you able to play Arte Live TV on their website ?
Thanks,

**Comment by wwark** [comment] 2021-03-08 16:19
[plugin.video.catchuptvandmore-testartetv5monde.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/6102687/plugin.video.catchuptvandmore-testartetv5monde.zip)
OK. Could you please test this plugin I add some logs to get the response from the server of Arte and TV5Monde ? Maybe we will have some information from those servers.
The test to perform is:
* Install this version
* Stop Kodi
* Start Kodi
* Test Live TV Arte and TV5Monde
* Stop Kodi
* Retreive the kodi.log and provide the whole log.
Thanks,

**Comment by Rvhalewyn** [comment] 2021-03-08 16:53
Done. Seems there are 2 different issues for Arte and TV5Monde.
.Should I keep this version, or go back to the previous?

Met vriendelijke groeten
Rudy Vanhalewyn
Contactpersoon voor België van
Stichting Projecthulp Suriname
W. Churchilllaan 23 bus 14
B-8300 Knokke-Heist

tel. +32 496 84 72 74 of +32 50 94 61 28
tel. vanuit Suriname 750 37 47
tel. vanuit Nederland +31 6 377 22 746
Viber +316 377 22 746
WhatsApp +316 377 22 746
sip:rvhalewyn@pbxes.org
LinkedIn Rudy Vanhalewyn




Op ma 8 mrt. 2021 om 17:19 schreef Marc Roy <notifications@github.com>:

**Comment by wwark** [comment] 2021-03-08 17:03
This version is just for getting more logs. You can keep it because it will update on the next version.
I don't receive the log.
Thanks.

**Comment by Rvhalewyn** [comment] 2021-03-08 17:07
Sent it and resending now as an attachment..
Met vriendelijke groeten
Rudy Vanhalewyn
Contactpersoon voor België van
Stichting Projecthulp Suriname
W. Churchilllaan 23 bus 14
B-8300 Knokke-Heist

tel. +32 496 84 72 74 of +32 50 94 61 28
tel. vanuit Suriname 750 37 47
tel. vanuit Nederland +31 6 377 22 746
Viber +316 377 22 746
WhatsApp +316 377 22 746
sip:rvhalewyn@pbxes.org
LinkedIn Rudy Vanhalewyn




Op ma 8 mrt. 2021 om 18:03 schreef Marc Roy <notifications@github.com>:

**Comment by wwark** [comment] 2021-03-08 17:17
Still no attachment maybe it is not possible to send them by mail in your response on the github issue.

Thanks,

**Comment by Rvhalewyn** [comment] 2021-03-08 17:20
Trying with Dropbox
https://www.dropbox.com/sh/r0fefj30yz0vh3b/AABP7xKsLV6yNNq8VoQiqLlEa?dl=0

Met vriendelijke groeten
Rudy Vanhalewyn
Contactpersoon voor België van
Stichting Projecthulp Suriname
W. Churchilllaan 23 bus 14
B-8300 Knokke-Heist

tel. +32 496 84 72 74 of +32 50 94 61 28
tel. vanuit Suriname 750 37 47
tel. vanuit Nederland +31 6 377 22 746
Viber +316 377 22 746
WhatsApp +316 377 22 746
sip:rvhalewyn@pbxes.org
LinkedIn Rudy Vanhalewyn




Op ma 8 mrt. 2021 om 17:19 schreef Marc Roy <notifications@github.com>:

**Comment by wwark** [comment] 2021-03-08 17:32
Sorry the log provided doesn't have the issue from the previous log.
It seems also no test to play contents on this log.
The kodi.log rotates to Kodi.log.old each time you start Kodi and the previous kodi.log.old is removed.
Maybe your test is in the other log if you start again kodi before to retreive log.
Thanks.

**Comment by Rvhalewyn** [comment] 2021-03-08 18:43
In order to simplify the enormous log, I disabled VPN Manager and IPTV Recorder before testing, that's why the current log is smaller. But it is the right log, made at 17.42.
I see a gap between 17.42 and 17.45. Seems Indigo interfering. Tomorrow I'll try again, disabling Indigo.

Anyhow, for Arte I got a Line-up Error or something , for TV5Monde a 404.

Kind regards
Rudy Vanhalewyn 
Winston Churchilllaan 23 bus 14 
B-8300 Knokke-Heist 
BELGIUM 



-------- Origineel bericht --------
Van: Marc Roy <notifications@github.com>
Verzonden: 8 maart 2021 18:32:32 CET
Aan: "Catch-up-TV-and-More/plugin.video.catchuptvandmore" <plugin.video.catchuptvandmore@noreply.github.com>
CC: Rvhalewyn <Rudy.Vanhalewyn@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Arte (F) and Tv5 Monde KO  (#462)

Sorry the log provided doesn't have the issue from the previous log.
It seems also no test to play contents on this log.
The kodi.log rotates to Kodi.log.old each time you start Kodi and the previous kodi.log.old is removed.
Maybe your test is in the other log if you start again kodi before to retreive log.
Thanks.

**Comment by Rvhalewyn** [comment] 2021-03-09 12:51
This log should be useful.
https://www.dropbox.com/sh/r0fefj30yz0vh3b/AABP7xKsLV6yNNq8VoQiqLlEa?dl=0


Op ma 8 mrt. 2021 om 18:32 schreef Marc Roy <notifications@github.com>:

**Comment by wwark** [comment] 2021-03-09 13:18
Thank you we have something in this log:

for TV5Monde your get HTTP 403 (not authorized)
It is the link of "http://v3fbs247hls-i.akamaihd.net/hls/live/219079/v3fbs247hls/index.m3u8"
2021-03-09 13:27:16.391 T:3205444464   DEBUG: Previous line repeats 1 times.
2021-03-09 13:27:16.391 T:3205444464   DEBUG: [urllib3.connectionpool] http://live.tv5monde.com:80 "GET /fbs.html HTTP/1.1" 200 3947
2021-03-09 13:27:16.413 T:3205444464   DEBUG: u'{"files":[{"format":"m3u8","url":"http:\\/\\/v3fbs247hls-i.akamaihd.net\\/hls\\/live\\/219079\\/v3fbs247hls\\/index.m3u8"}],"primary":"html5","token":false}'
2021-03-09 13:27:16.442 T:3205444464   DEBUG: [urllib3.connectionpool] Starting new HTTP connection (1): v3fbs247hls-i.akamaihd.net:80
2021-03-09 13:27:16.684 T:3205444464   DEBUG: [urllib3.connectionpool] http://v3fbs247hls-i.akamaihd.net:80 "GET /hls/live/219079/v3fbs247hls/index.m3u8 HTTP/1.1" 403 347
2021-03-09 13:27:16.705 T:3205444464   ERROR: [Catch-up-TV-&-More.support] 403 Client Error: Forbidden for url: http://v3fbs247hls-i.akamaihd.net/hls/live/219079/v3fbs247hls/index.m3u8

Could you please try it "http://v3fbs247hls-i.akamaihd.net/hls/live/219079/v3fbs247hls/index.m3u8" on your PC with VLC and after that create a file test.m3u with the url on it and play the m3u file on Kodi ?

For Arte It Is the same, no stream available in the response from the server:

> {
  "data": {
    "id": "098995-047-A_de",
    "type": "ConfigPlayer",
    "attributes": {
      "provider": "arte",
      "metadata": {
        "providerId": "098995-047-A",
        "language": "de",
        "title": "Stadt Land Kunst",
        "subtitle": "Maurice Denis und Perros-Guirec \\/ Milos \\/ Tansania \\/ T\\u00e9touan",
        "description": "Linda Lorin l\\u00e4dt auf eine Reise an vier besondere Orte ein, die sich durch ihr k\\u00fcnstlerisches, kulturelles oder landschaftliches Erbe auszeichnen. In dieser Folge: Maurice Denis: Ein Nabi in Perros-Guirec \\/ Milos: Von Vulkanen und Menschen auf den Kykladen\\u00a0\\/ Tansania: Zeanas Karamellbonbons \\/ Die K\\u00f6nigin von T\\u00e9touan",
        "images": [
          {
            "caption": "Perros-Guirec liegt an der Nordk\\u00fcste Frankreichs, im franz\\u00f6sischen D\\u00e9partement C\\u00f4tes-d\\u2019Armor. Ende des 19. Jahrhunderts schlug diese unber\\u00fchrte Natur der Bretagne zwischen Wasser und Land den Maler Maurice Denis in ihren Bann.",
            "url": "https:\\/\\/api-cdn.arte.tv\\/api\\/mami\\/v1\\/program\\/de\\/098995-047-A\\/940x530?ts=1614614990"
          }
        ],
        "link": {
          "url": "https:\\/\\/www.arte.tv\\/de\\/videos\\/098995-047-A\\/stadt-land-kunst\\/",
          "deeplink": "arte:\\/\\/program\\/098995-047-A",
          "videoOnDemand": null
        },
        "config": {
          "url": "https:\\/\\/api.arte.tv\\/api\\/player\\/v2\\/config\\/de\\/098995-047-A",
          "replay": null,
          "playlist": "https:\\/\\/api.arte.tv\\/api\\/player\\/v2\\/playlist\\/de\\/LIVE?liveProgramId=098995-047-A"
        },
        "duration": {
          "seconds": 2710
        }
      },
      "live": true,
      "chapters": null,
      "rights": {
        "begin": "2021-03-09T12:01:24+00:00",
        "end": "2021-03-09T12:46:34+00:00"
      },
      "streams": [],
      "stat": {
        "eStat": {
          "level1": "CPO_kultur-und-pop",
          "level2": "LIVE_ANTENNE",
          "level3": "de",
          "level4": "ART_kunst",
          "level5": "098995-047-A",
          "mediaChannel": "18",
          "mediaContentId": "098995-047-A",
          "mediaDiffMode": "LIVE",
          "newLevel1": "LIVE",
          "newLevel11": "424_magazine-quotidien-de-l-apres-midi",
          "newLevel2": "manual",
          "newLevel3": "-",
          "newLevel4": "-",
          "streamDuration": 0,
          "streamGenre": "a",
          "streamName": "Stadt Land Kunst",
          "serial": 266066213484,
          "prerollSerial": 213013217336
        },
        "arte": {
          "tablet": {
            "WEB": "https:\\/\\/www.arte.tv\\/pa\\/api\\/multimedia\\/v1\\/098995-047\\/A\\/de\\/LIVE\\/TABLET\\/WEB\\/arte.gif"
          },
          "desktop": {
            "WEB": "https:\\/\\/www.arte.tv\\/pa\\/api\\/multimedia\\/v1\\/098995-047\\/A\\/de\\/LIVE\\/DESKTOP\\/WEB\\/arte.gif"
          },
          "mobile": {
            "WEB": "https:\\/\\/www.arte.tv\\/pa\\/api\\/multimedia\\/v1\\/098995-047\\/A\\/de\\/LIVE\\/MOBILE\\/WEB\\/arte.gif"
          }
        },
        "agf": {
          "type": "content",
          "assetid": "livestream_247",
          "program": "424_magazine-quotidien-de-l-apres-midi",
          "title": "stadt-land-kunst",
          "length": 86400,
          "nol_c2": "p2,N",
          "nol_c5": "p5,https:\\/\\/www.arte.tv\\/de\\/videos\\/098995-047-A\\/stadt-land-kunst\\/",
          "nol_c7": "p7,livestream_247",
          "nol_c8": "p8,86400",
          "nol_c9": "p9,Arte247Livestream",
          "nol_c10": "p10,ARTE",
          "nol_c12": "p12,Content",
          "nol_c15": null,
          "nol_c18": "p18,Y"
        }
      },
      "ads": {
        "adtech": null,
        "smart": {
          "url": "https:\\/\\/www14.smartadserver.com\\/ac?siteid=307555&pgid=1115590&fmtid=81409&ab=1&tgt=cat%3DCPO_ART%3Blang%3Dde&oc=1&out=vast4&ps=1&pb=0&visit=S&vcn=s&ctid=098995-047-A&ctd=2710&lang=de&ctt=broadcast&ctc=CPO_ART&ctk="
        }
      },
      "restriction": {
        "enablePreroll": true,
        "geoblocking": {
          "code": "DE_FR",
          "restrictedArea": true,
          "userGeoblockingZone": [
            "EUR_DE_FR",
            "SAT",
            "ALL"
          ]
        },
        "ageRestriction": "NONE",
        "allowEmbed": true,
        "enableMyArte": false
      },
      "stickers": [
        {
          "code": "LIVE",
          "label": "LIVE"
        }
      ],
      "autoplay": true
    }
  }
}

I don't know why you have this return but the server refuse to propose streams on your side ....
If it is possible could you please try to install the addon CUTV&More in a clean install of Kodi with just the addon to see if those isssues remains.

Thanks,

**Comment by Rvhalewyn** [comment] 2021-03-09 14:26
I installed Kodi 18.4 on Windows 10 on my pc, with only the CUTV addon.
Exactly the same as on my LibrELC device: List index error (what is that?),
only for Arte!
The other channels work.

I tried the TV5M link on VLC. "Cannot be opened"
Wrong link perhaps?


Op di 9 mrt. 2021 om 14:18 schreef Marc Roy <notifications@github.com>:

**Comment by wwark** [comment] 2021-03-09 14:37
For the moment, we will focus on the case of TV5M.

I tried again the link http://v3fbs247hls-i.akamaihd.net/hls/live/219079/v3fbs247hls/index.m3u8 and it is working on my side on VLC.
Maybe vlc get HTTP 403 on your side (you can launch cvlc to get logs in the console).
Did you open it in this menu ?
![image](https://user-images.githubusercontent.com/469461/110486666-23227f80-80ed-11eb-97da-e23482a1d486.png)

So in your new install of Kodi you have TV5Monde working, is it the same PC  you test on VLC ? What is the differences with your other kodi instance ?

Thanks,

**Comment by wwark** [comment] 2021-03-09 15:04
Sorry I misread your previous post.
If the live TV of TV5Monde working on your web browser in the same network of your kodi instances, could you please provide a HAR file of a test to play the direct TV of TV5Monde ? 
We will verify if the content url is different and how your web browser handle to play it.
Some informations to produce this file:
https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting

Thanks,

**Comment by Rvhalewyn** [comment] 2021-03-09 16:41
https://www.dropbox.com/sh/r0fefj30yz0vh3b/AABP7xKsLV6yNNq8VoQiqLlEa?dl=0
Is it possible one should register for that channel?
My version of CU does not allow so.
By the way, I would appreciate to be able to register also for NPO as I
have a paid subscription to get HD resolution.




Op di 9 mrt. 2021 om 16:04 schreef Marc Roy <notifications@github.com>:

**Comment by wwark** [comment] 2021-03-09 17:19
For the moment, we don't implement contents required paid subscription because it means we need to get subscription to test the code to add it and keep subscription for the support.
We implement register if it is needed to access to the content.
Your log is for TV5 Monde Afrique am I right ? What will be the benefit to implement register part, do you have access are more free contents ?

Thanks,

**Comment by wwark** [comment] 2021-03-09 18:29
TV5Monde works without account. The HAR file from your browser will help for this suject.

Arte, the erros means we can't find any stream on your case. I need to implement a notification to inform the use no stream available in this case.
I will prepare the steps maybe difficult to follow on your web browser to see if we manage to get stream.

BBC there is already a great addon and German channels it is difficult for the moment to add more channels and maintain existing one if we have more people on the project we can add more channels maybe in the future.

Thanks,

**Comment by Rvhalewyn** [comment] 2021-03-09 18:33
Thanks, good luck and keep on the good work! 


-------- Origineel bericht --------
Van: Marc Roy <notifications@github.com>
Verzonden: 9 maart 2021 19:29:50 CET
Aan: "Catch-up-TV-and-More/plugin.video.catchuptvandmore" <plugin.video.catchuptvandmore@noreply.github.com>
CC: Rvhalewyn <Rudy.Vanhalewyn@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Arte (F) and Tv5 Monde KO  (#462)

TV5Monde works without account. The HAR file from your browser will help for this suject.

Arte, the erros means we can't find any stream on your case. I need to implement a notification to inform the use no stream available in this case.
I will prepare the steps maybe difficult to follow on your web browser to see if we manage to get stream.

BBC there is already a great addon and German channels it is difficult for the moment to add more channels and maintain existing one if we have more people on the project we can add more channels maybe in the future.

Thanks,

**Comment by wwark** [comment] 2021-03-14 10:18
Test to be done with your web browser.
It is the way it is done by the plugin to get the live stream.

1 - open a tab in your web browser at this url : https://reqbin.com/
2 - open a second tab in your web browser at this url : https://static-cdn.arte.tv/guide/manifest.js
3 - In the tab, you need to retrieve a token, you need to search "token" in it and you need to take the first one (like below)
![image](https://user-images.githubusercontent.com/469461/111064508-ac063600-84b4-11eb-99ce-8a0eae8f8600.png)
This token is valid for few times so the next step needs to be done in less than 5 minutes.
4 - In the first tab, you need to fill the URL, in the onglet header you need to set Authorization: Bearer TOKEN_RETRIEVE_ON_3rd_STEP and click on send.
![image](https://user-images.githubusercontent.com/469461/111064861-c17c5f80-84b6-11eb-8bbe-c5fcb31aa2fa.png)

**Comment by Rvhalewyn** [comment] 2021-03-14 17:08
I did exactly what you asked.
Got Status:401 (Unauthorized)Time:418 msSize:0.56 kb



Op zo 14 mrt. 2021 om 11:18 schreef Marc Roy ***@***.***>:

**Comment by Rvhalewyn** [comment] 2021-03-14 17:24
You find the test here
https://www.dropbox.com/sh/r0fefj30yz0vh3b/AABP7xKsLV6yNNq8VoQiqLlEa?dl=0



-------- Origineel bericht --------
Van: Marc Roy ***@***.***>
Verzonden: 14 maart 2021 11:18:22 CET
Aan: "Catch-up-TV-and-More/plugin.video.catchuptvandmore" ***@***.***>
CC: Rvhalewyn ***@***.***>, Author ***@***.***>
Onderwerp: Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Arte (F) and Tv5 Monde KO  (#462)

Test to be done with your web browser.
It is the way it is done by the plugin to get the live stream.

1 - open a tab in your web browser at this url : https://reqbin.com/
2 - open a second tab in your web browser at this url : https://static-cdn.arte.tv/guide/manifest.js
3 - In the tab, you need to retrieve a token, you need to search "token" in it and you need to take the first one (like below)
![image](https://user-images.githubusercontent.com/469461/111064508-ac063600-84b4-11eb-99ce-8a0eae8f8600.png)
This token is valid for few times so the next step needs to be done in less than 5 minutes.
4 - In the first tab, you need to fill the URL, in the onglet header you need to set Authorization: Bearer TOKEN_RETRIEVE_ON_3rd_STEP and click on send.
![image](https://user-images.githubusercontent.com/469461/111064861-c17c5f80-84b6-11eb-8bbe-c5fcb31aa2fa.png)

**Comment by wwark** [comment] 2021-03-14 18:31
If you get HTTP 401 it means you are blocked by the server.
But it will be difficult to know why the reason is on the server side ...
In the last logs we continue to see you can't access to those contents.
I don't know what to do for your case maybe a configuration (VPN, proxy or something in your kodi or your network ...)
Thanks,

**Comment by Rvhalewyn** [comment] 2021-03-14 19:46
Thanks for all the searching.

There is perhaps one more clue. 
The 3 channels I don't get, are exactly the only 3 that I chose from CU, for which one has to select the language or version.
So Arte: F or D
Tele5Monde: France... or Africa or...
France 3 Régions

All other channels I picked have no problem, France 2 to 5, TF1, Belgian channels,... All of these have only 1 version!

Could that be the reason, and if so, could there be a bug in programming the language or version? Some symbol not accepted in Kodi 18?


-------- Origineel bericht --------
Van: Marc Roy ***@***.***>
Verzonden: 14 maart 2021 19:31:49 CET
Aan: "Catch-up-TV-and-More/plugin.video.catchuptvandmore" ***@***.***>
CC: Rvhalewyn ***@***.***>, Author ***@***.***>
Onderwerp: Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Arte (F) and Tv5 Monde KO  (#462)

If you get HTTP 401 it means you are blocked by the server.
But it will be difficult to know why the reason is on the server side ...
In the last logs we continue to see you can't access to those contents.
I don't know what to do for your case maybe a configuration (VPN, proxy or something in your kodi or your network ...)
Thanks,

**Comment by wwark** [comment] 2021-03-16 06:33
The language is not the issue here.

The production of a HAR file on your web browser like describe in this comment https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/462#issuecomment-794016598 will help to understand how your web browser can play Arte Live TV.

Thanks,

**Comment by wwark** [comment] 2021-03-30 11:59
Hi @Rvhalewyn,
Are you able to produce the HAR File ?
If it is not the case we propose to close this ticket.
Thanks.

**Comment by Rvhalewyn** [comment] 2021-04-01 13:37
You find the test here
https://www.dropbox.com/sh/r0fefj30yz0vh3b/AABP7xKsLV6yNNq8VoQiqLlEa?dl=0

**Comment by wwark** [comment] 2021-04-02 21:28
Thanks.
On har trace of TV5 Monde you are also not authorized to play the stream
![image](https://user-images.githubusercontent.com/469461/113455461-f66f3880-940a-11eb-8512-51a2a5fb1537.png)
So you can't play those contents with your connection.
Until you have HTTP 403 in your browser, it means you will have the same issue in Kodi.
I can't do more for your case.

I proposed to close this ticket.

**Comment by wwark** [comment] 2021-04-09 15:46
Ticket closed !

**Closed by wwark** 2021-04-09 15:46 UTC
