### ISSUE TITLE
United Kingdom Channel 4 

### ISSUE THREAD

**Issue by marson53** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1176] opened 2023-07-18 17:48 UTC
When playing any video content on Channel 4 there is always Audio description that plays  , Is there any settings in the add-on to turn this off Thanks.               Kodi 20.2 Catch-up TV ver 0.2.39 beta28

**Comment by joaopa00** [comment] 2023-07-19 20:15
Deserves a try: 
![Screenshot_20230719_101457](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/13057733/157c2a08-2e23-4e42-a857-560f116c476f)

**Comment by marson53** [comment] 2023-07-19 22:46
I have found out how to turn the audio description off now, when playing any content from Channel 4 , click ok button when playing video to get the menu up , then click the audio menu, click audio stream, there are 2 audio streams ,click  the one that says [Unknown] - AAC - 2 channels [default] (1/2) , This will turn off Audio Discription

**Comment by joaopa00** [comment] 2023-07-20 05:44
Thanks for the feedback. Since the problem is fixed, I close this issue.

**Closed** 2023-07-20 06:04 UTC
