### ISSUE TITLE
UKTV Catchup - Error when attempting playback

### ISSUE THREAD

**Issue by techionltd** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#541] opened 2021-07-21 22:50 UTC
### Describe the bug
When trying to watch UK catchup TV, playback fails and throws error :-
"This selection triggered an unexpected error, would you like to
share your error log so that we can try and resolve this issue"

1. Open plugin
2. Navigate "Catchup TV" > "United Kingdom" > "UKTV Play" > "UK Drama" > "The Bill".
3. Attempt playback of any of the listed episodes to create the error

### Expected behavior
Normally, plays episodes without issue

### Actuel behavior
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Linux

 - Operating system version/name: Ubuntu 20.04.2 LTS
 - Kodi version: 18.9
 - Catch-up TV & More version: 0.2.35
 - Installation method: github repo source

### Debug log
2021-07-21 23:41:21.558 T:139619278497536   ERROR: [Catch-up-TV-&-More.support] local variable 'data_account' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                redirect = parent_ins(route, arg_params, self.callback_params)
                                              File "/home/kodi/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                results = super(Resolver, self).__call__(route, args, kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                return route.function(self, *args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/uk/uktvplay.py", line 270, in get_video_url
                                                URL_BRIGHTCOVE_VIDEO_JSON % (data_account, data_video_id),
                                            UnboundLocalError: local variable 'data_account' referenced before assignment  

Full debug log @ https://zerobin.net/?b2824fe804a77b71#rm7YR6Sgfh9GFwJ5Edx2CfM93011t18z3ki1A5OW1Kg=

**Comment by northernpowerhouse** [comment] 2021-08-05 09:24
I'm getting the same error on kodi 19 on an nvidia shield, by the way

**Comment by DoctorOctagonapus** [comment] 2021-09-05 18:48
Nothing from UKTV will play apparently, login credentials don't appear to make a difference. I'm getting the same thing on LibreELEC 9.2.8 on Pi4

**Comment by naszdom** [comment] 2021-10-19 19:07
It's been like this for a few months.  There is nothing we can do but to hope someone can up date it.

**Comment by Arkadia2008** [comment] 2021-11-21 12:14
Is anyone working on a fix?

**Comment by jamieburchell** [comment] 2021-12-01 21:59
I'm not a Python developer, but know enough to be dangerous. First problem I can see is the regex for scrapping js files:

`uktv\-static\/prod\/play\/(.*?)\.js`

The source of the page shows "fgprod" now. Unfortunately, that alone doesn't resolve the issue. It seems that VUE_APP_BRIGHTCOVE_ACCOUNT and VUE_APP_BRIGHTCOVE_PLAYER aren't being found and set, hence the error. I manually entered the correct values for these based on my login, but faced another issue:

`InputStream Adaptive: Unable to load widevine shared library (/home/osmc/.kodi/cdm/libwidevinecdm.so)`

Maybe others will have more luck.

**Comment by kevwag** [comment] 2021-12-02 11:23
@jamieburchell  you, sir are a genius and a legend!
This problem has been a real crappy one and it's gone-on for months causing my sanity to evaporate almost completely!

Despite my having no Python skills whatsoever I was able to fix this in minutes, simply by pasting your code into the file (ok, so there was an error at first but it was fairly self-explanatory and I just had to add a space to the start of each of the three new lines of code).

Thank you massively for taking the time to figure this out and even more so for sharing the solution with the rest of us here - it's clearly not something the addon's devs were in any hurry to care about.

**Comment by techionltd** [comment] 2021-12-02 12:02
@jamieburchell, thanks so much for this.
So glad someone found a solution.

kodi.tv make a big song and dance about using their 'official' addons, otherwise you forego any support, and yet when we do use their addons, they don't give any support when it comes to an issue that's been open for five months.

Anyway, well done sir. Hopefully their dev will now do a copy/paste and finally issue an official update

**Comment by jamieburchell** [comment] 2021-12-02 12:20
Excellent, glad it's working. The problem with code like this that scrapes content is that it breaks as soon as the output of the website changes, as was the case here. It may well break again when the content changes again.

**Comment by jamieburchell** [comment] 2021-12-02 12:32
> (ok, so there was an error at first but it was fairly self-explanatory and I just had to add a space to the start of each of the three new lines of code).

Whoops. Fixed that in my comment!

**Comment by berkhornet** [comment] 2021-12-04 09:08
> > (ok, so there was an error at first but it was fairly self-explanatory and I just had to add a space to the start of each of the three new lines of code).
> 
> Whoops. Fixed that in my comment!
> 
> Excellent, glad it's working. The problem with code like this that scrapes content is that it breaks as soon as the output of the website changes, as was the case here. It may well break again when the content changes again.
> 
> I'm also reluctant to create a PR for this, as I'd never written any Python a couple of hours prior to looking at it, so there's probably better ways of fixing this. I don't know how exactly the devs want to fix the issue.

@jamieburchell Many thanks for the fix. I would raise a PR and then the author of the addon can accept/reject/amend your code as they see fit. Great to have UKTV Play working again.

**Comment by jamieburchell** [comment] 2021-12-04 18:07
Sorry for all the noise, [this](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/590/commits/02142b79a1859f8a2aa1189e99ca96ddd635f8c7) is now the final proposed fix.

**Comment by nictjir** [comment] 2022-01-21 06:58
Thankyou @jamieburchell the final proposed fix works for me! Much appreciated.

**Comment by kevwag** [comment] 2022-02-16 04:25
I'm a bit unsure how all this commit / merge stuff works, could someone break it down for me please?

I see on this thread that something was "merged" on 4th Dec 2021 and something was "committed" 25 days ago but the main GitHub page is still showing the latest release as being 21st October 2021 - before any of this happened. This release will obviously still be un-fixed so what happens now?

I'm currently running the dev version with the fix manually applied but obviously this means I won't receive any updates or update notifications so it's less than ideal. Will a new, fixed release be available any time soon? Also, will the fixed release be updated in the official Kodi repo at the same time or is it better to add it from the repo here?

**Comment by nictjir** [comment] 2022-02-16 05:31
The "fix" allowed me to watch catchup TV only, did not fix the live TV playback
My Kodi is running on an rooted Android TV box
What i did to use the fix was to edit
/storage/emulated/0/Android/org.xbmc.kodi/files/.kodi/addons/plugins/catchuptvandmore/resources/lib/channels/uk/uktvplay.py

with the changes shown in the diff at 
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/590/commits/02142b79a1859f8a2aa1189e99ca96ddd635f8c7

Removed the lines starting with -
Adding the lines starting with +

And restarted kodi.
[uktvplay.py.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8077016/uktvplay.py.zip)

**Comment by DoctorOctagonapus** [comment] 2022-02-16 10:11
If you're running LibreELEC, the path is /storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/uk/uktvplay.py

Can also confirm the fix works perfectly.

**Comment by kevwag** [comment] 2022-02-18 16:22
Yes, the "fix" only fixes the on-demand content and not the live TV channels but I think that's a bigger problem, not specifically linked to UKTV. 
NONE of the UK IPTV channels work and there is no EPG data either. It would be great if someone could find a fix for this. It would be even better if a UK focused dev would join this team and add more UK functionality to the addon. There are several free-to-use streaming platfoms run by UK Freeview operators that are not currently supported by any Kodi addons.
ITV Hub, All4, My5 and STV have no addons at all, there is a BBC iPlayer addon but parts of it don't work and it doesn't integrate the live channels into IPTV manager.  How awesome would it be if someone could add these services into a single addon?

**Comment by jamieburchell** [comment] 2022-02-18 16:33
Where is the live UKTV functionality in this plugin? I went looking for it but couldn't see anything.

**Comment by joaopa00** [comment] 2022-02-24 23:25
At least, replay should be fixed in the dev branch  since a long time.
You can download the zip file here:
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/archive/refs/heads/dev.zip

**Comment by kevwag** [comment] 2022-04-07 19:00
> > Yes, the "fix" only fixes the on-demand content and not the live TV channels
> 
> Where is the live UKTV functionality in this plugin? I went looking for it but couldn't see anything.

All the UKTV functionality, both Live and Catchup are all handled in the one file. Its name and location are referenced several times in this thread, there's also a download link for a semi-fixed version. Catchup is now fixed but the live channels produce a "list out of range" error. The problem seems to be with the regex in the last section of uktvplay.py but I don't know enough about regex or python to be able to fix it (I have tried extensively). 

The code basically builds a URL to stream from so the error could be caused by one of the base URLs changing (URL_STREAM_LIVE / URL_LIVE_KEY / URL_LIVE_TOKEN) or the context of the regex that follows them but I don't know how to capture these URLs from the original website for comparison. (it was simply adding "prod" within the latter part of the URL that fixed the catchup side of things so the live part is probably equally simple if you know what you're doing.).

**Comment by jamieburchell** [comment] 2022-04-07 19:57
> > > Yes, the "fix" only fixes the on-demand content and not the live TV channels
> > 
> > 
> > Where is the live UKTV functionality in this plugin? I went looking for it but couldn't see anything.
> 
> All the UKTV functionality, both Live and Catchup are all handled in the one file. Its name and location are referenced several times in this thread, there's also a download link for a semi-fixed version. Catchup is now fixed but the live channels produce a "list out of range" error. The problem seems to be with the regex in the last section of uktvplay.py but I don't know enough about regex or python to be able to fix it (I have tried extensively).
> 
> The code basically builds a URL to stream from so the error could be caused by one of the base URLs changing (URL_STREAM_LIVE / URL_LIVE_KEY / URL_LIVE_TOKEN) or the context of the regex that follows them but I don't know how to capture these URLs from the original website for comparison. (it was simply adding "prod" within the latter part of the URL that fixed the catchup side of things so the live part is probably equally simple if you know what you're doing.).

I actually meant where abouts in the plugin menu was it, because I thought I'd gone through every option and couldn't find anything that didn't work after I'd fixed catch-up.

**Comment by kevwag** [comment] 2022-04-07 20:04
> 

It's in Catch-Up >> United Kingdom >> UKTV Play
If you can't find it then you've probably hidden it and will need to go into the settings menu to un-hide it.

**Comment by jamieburchell** [comment] 2022-04-07 20:31
I'm away at the moment, but I could only find the catch up stuff in that area.

**Comment by kevwag** [comment] 2022-04-09 18:54
> I'm away at the moment, but I could only find the catch up stuff in that area.

Yes, hence Catch-up being the root menu.
The live channels are in Live TV >> United Kingdom.
Again, if they're not there you've probably hidden them and you'll need to un-hide them in the settings menu.
You can also add the channels to Kodi's EPG from the settings menu via IPTV Manager.

It's irrelevant at the moment anyway because none of the UKTV channels work. Some of the other UK channels do work but there's no guide data because the plugin tries to scrape outdated URLs at tvguide.co.uk

**Comment by jamieburchell** [comment] 2022-04-10 03:00
> The live channels are in Live TV >> United Kingdom.

I see. I use a DVB-T2 tuner for live TV so my setup is different.

**Comment by kevwag** [comment] 2022-04-11 19:03
> 

You obviously know what you're doing and I understand why you wouldn't want to waste your time fixing something you don't use but could you maybe confirm whether you think I'm looking in the right places or not? (Please!)

I don't have anywhere near the knowledge that you obviously have. The last time I did any serious coding was 1990 using Turbo Pascal so I'm more than a bit rusty but if I can, I'd really like to try and fix this for myself and everyone else that wants it. It's a long-shot and I probably won't solve it but right now it looks like I'm the only one willing to try.

**Comment by jamieburchell** [comment] 2022-04-11 19:40
> @jamieburchell You obviously know what you're doing and I understand why you wouldn't want to waste your time fixing something you don't use but could you maybe confirm whether you think I'm looking in the right places or not? (Please!)
> 
> I don't have anywhere near the knowledge that you obviously have. The last time I did any serious coding was 1990 using Turbo Pascal so I'm more than a bit rusty but if I can, I'd really like to try and fix this for myself and everyone else that wants it. It's a long-shot and I probably won't solve it but right now it looks like I'm the only one willing to try.

So as far as I thought, [this file I contributed to](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/dev/resources/lib/channels/uk/uktvplay.py)  was specifically for UKTV Play catch up. I don't know about the live TV part. But in general I'd probably look at what requests are made in a browser when viewing the live TV channels on the web and work backwards from there.

**Comment by kevwag** [comment] 2022-04-11 20:39
> > @jamieburchell You obviously know what you're doing and I understand why you wouldn't want to waste your time fixing something you don't use but could you maybe confirm whether you think I'm looking in the right places or not? (Please!)
> > I don't have anywhere near the knowledge that you obviously have. The last time I did any serious coding was 1990 using Turbo Pascal so I'm more than a bit rusty but if I can, I'd really like to try and fix this for myself and everyone else that wants it. It's a long-shot and I probably won't solve it but right now it looks like I'm the only one willing to try.
> 
> So as far as I thought, [this file I contributed to](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/dev/resources/lib/channels/uk/uktvplay.py) was specifically for UKTV Play catch up. I don't know about the live TV part. But in general I'd probably look at what requests are made in a browser when viewing the live TV channels on the web and work backwards from there.

The file does both. The catchup part ends after line 292. and then the live part starts on line 296:

def get_live_url(plugin, item_id, **kwargs):

I'm really stuck with the browser part. I use "inspect" from the context menu to open the dev tools and then my head explodes! I've spent hours, no, days trying to fathom out where to look!

**Comment by jamieburchell** [comment] 2022-04-11 22:33
> I've spent hours, no, days trying to fathom out where to look!

I would create a new issue with as much detail as you can provide (preferably following the issue template) because this issue is for catch-up only.

**Comment by joaopa00** [comment] 2022-04-12 02:05
Is the issue fixed for the catch-up part ?
If yes, one could close this issue and it would be better to open a new one for the lives.

**Comment by joaopa00** [comment] 2022-04-12 16:53
I am closing this issue. Please, open again if the problem persists.

**Closed by joaopa00** 2022-04-12 16:53 UTC
