### ISSUE TITLE
FRANCE TV a free account is now requested to access replay and live TV ?

### ISSUE THREAD

**Issue by jlb312** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1285] opened 2024-02-29 14:45 UTC
It seems that a free account with login and password is requested in order to access FRANCE TV server. 

Is anyone can confirm this ?

Regards

**Comment by sebmourlhou** [comment] 2024-02-29 23:19
I confirm !

**Comment by crocketear** [comment] 2024-03-01 04:39
Je confirme également.
Comment fait-on pour intégrer notre compte dans CatchUpTV&More vu qu'il n'y a pas de compte france.tv dans les paramètres ?

**Comment by willow3411** [comment] 2024-03-01 19:37
Bonsoir à tous,
pareil sous RPI4 Libreelec derniere version et KODI 20....

**Comment by IceFreak66** [comment] 2024-03-01 20:43
[resolver_proxy.py.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14465791/resolver_proxy.py.txt)

For the time being, I could only fix the live stream of FranceTV

**Comment by IceFreak66** [comment] 2024-03-01 21:54
So I've been able to get as far as getting links ending in .dash for the replay videos, but I end up in an inputadaptive error when trying to stream it with a message no MOOV in stream

And that goes beyond what I know. So if someone comes by with an idea, I'd be happy to discuss it.

**Comment by IceFreak66** [comment] 2024-03-01 22:29
So, perseverance was key.

I'm attaching a new version of the resolver_proxy.py file. Simply replace the one in the addon folder and it should repair both live and replay France TV. (remember to change the extension back to .py)
[resolver_proxy.py.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14466635/resolver_proxy.py.txt)

**Comment by darkb1967** [comment] 2024-03-02 08:47
Hello, thank you IceFreak66 for your file. Now a gift for easy use (stick and nvidiashiel...). I've modified addon and put in new resolver. Cadeau pour vous les gars fichier a ajouter dans kodi
[plugin.video.catchuptvandmore-0.2.40~b1_modf2.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14468617/plugin.video.catchuptvandmore-0.2.40.b1_modf2.zip)

France TV marche a nouveau. All work perfectly..

**Comment by IceFreak66** [comment] 2024-03-02 08:50
Just a FYI, it's not really a durable fix. I found out that if you make france tv think you use a safari browser, it returns only m3u8 feeds. So it works that way.
But dash-mpeg streams are still broken and need someone more knowledgable than me to adress.

**Comment by calvin4242** [comment] 2024-03-03 12:11
Thank you, this fix works perfectly, just replaced "resolver_proxy.py" from catchup extension by the one in zip file.
Could someone consider the possibility of creating an account credentials in catchup account settings for a permanent fix pleas
e?

**Comment by IceFreak66** [comment] 2024-03-03 13:25
> Thank you, this fix works perfectly, just replaced "resolver_proxy.py" from catchup extension by the one in zip file. Could someone consider the possibility of creating an account credentials in catchup account settings for a permanent fix pleas e?

There's actually no need for that, the issue was a missing parameter in an http call (probably after a change in API from FranceTV) which I added. All feeds can be retrieved without the need for an account at all.

The one issue remaining is about the dash-mpeg so that we don't need to force the call to be made with the browser param set to safari

**Comment by wilfarte** [comment] 2024-03-03 14:11
Thank you. All is fine on my nvidia shield with the py file transfered.

**Comment by DavidC-75** [comment] 2024-03-03 22:18
> It seems that a free account with login and password is requested in order to access FRANCE TV server.

> There's actually no need for that, the issue was a missing parameter in an http call (probably after a change in API from FranceTV) which I added. All feeds can be retrieved without the need for an account at all.

I'm not too sure if that's the very same issue or not, but something similar was reported and fixed (tried it myself) here :
https://github.com/melmorabity/plugin.video.francetv/issues/9

> The one issue remaining is about the dash-mpeg....

Again, no idea if the fix above already addresses that too or not...

**Comment by fonkdoctor** [comment] 2024-03-05 19:48
Hello all,
Merci @IceFreak66 pour le fichier resolver_proxy.py, ça marche impeccable sur windows ;)

Merci @Olivier1967 pour ton zip, j'ai bien installé ta version updatée dans kodi et ça fonctionne :)
Par contre j'ai un soucis de coupure de flux, ça charge à peu près toutes les 10secondes (pas de soucis sur windows)... ça parle à quelqu'un ? 

Merci et très bonne journée à tous !

**Comment by sebmourlhou** [comment] 2024-03-05 23:15
This version works with the dash-mpeg streams :
[resolver_proxy.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14502417/resolver_proxy.txt)

But sometimes the video doesn't start (infinite loading) when I switch between series or episodes.
I have to restart Kodi...
Launching the very first video works every time though.

I have exactly the same problem with the france.tv plugin (with the fix mentioned by DavidC-75), so maybe it's my computer (Windows).

Can anyone try?

**Comment by IceFreak66** [comment] 2024-03-06 10:31
Hello @SebMourlhou 

Do you mind if I take your file and take a look into making it more stable ?

**Comment by sebmourlhou** [comment] 2024-03-06 11:06
Sure you can

**Comment by IceFreak66** [comment] 2024-03-06 12:24
So, I found the error, but I don't know how to adress it.
Issue occurs in the libCurl library

When it works, it's because the curl command to retreive the manifest.md file is done with the proper user agent.

When it fails, it's because the request is done with the user agent : Kodi/20.4 (Windows NT 10.0.22631.3235; Win64; x64) App_Bitness/64 Version/20.4-(20.4.0)-Git:20240211-4868e9c709
That curl request returns 403

But I have no idea why curl would change the user-agent at random points. I'm gonna delve a little more into it

Edit : The issue is somewhere in inputstream.adaptive, I can't look into it any further

**Comment by IceFreak66** [comment] 2024-03-06 13:28
From inputstream adaptive github :

Fix inputstream.adaptive.manifest_params which params was not applied to manifest request in 21.4.3-Omega

So I'm pretty sure that's the source of the problem.

**Comment by IceFreak66** [comment] 2024-03-06 17:02
I can confirm it's working in Kodi 21 beta 3

**Comment by pols12** [comment] 2024-03-08 23:14
Note: SebMourlhou’s patch requires nonfree Widevine DRM support, whereas I can watch movies without Widevine thanks to IceFreak66’s patch.

**Comment by joaopa00** [comment] 2024-03-13 09:36
@pols12 for the same program?

**Comment by IceFreak66** [comment] 2024-03-13 09:43
> @pols12 for the same program?

Yeah, that's normal. My patch is forcing the request to be made as a safari browser. When you do that, france tv servers only return hls streams for every program.
SebMourlhou’s made it so that it requests as firefox, but handles properly dash mpegs streams as well. Except for an issue in inputstream adaptive that was fixed in kodi 21

**Comment by joaopa00** [comment] 2024-03-13 09:53
With safari browser, only hls streams are available?
The advantage of hls stream is they are downloadable when there is no drm.

**Comment by IceFreak66** [comment] 2024-03-13 09:56
> With safari browser, only hls streams are available? The advantage of hls stream is they are downloadable when there is no drm.

I tested out a lot of programs, and I only ever got hls back when querying as safari. I cannot conclusively say safari browser will only ever get hls, but it seems that way at least.

**Comment by joaopa00** [comment] 2024-03-13 10:07
Can you try taxi driver in category - cinema -suspense
as well as with your patch and with Sebmourlhou's one. I would be surprised there is no drm in this stream.

**Comment by IceFreak66** [comment] 2024-03-13 10:17
Running as chrome : 

"video": {
        "workflow": "token-akamai",
        "token": "https://hdfauth.ftven.fr/esi/TA?format=json",
        "duration": 6559,
        "embed": false,
        "format": "dash",
        "is_live": false,
        "drm": false,
        "drm_type": null,
        "license_type": null,
        "spritesheets": [

Running as safari :

"video": {
        "workflow": "token-akamai",
        "token": "https://hdfauth.ftven.fr/esi/TA?format=json",
        "duration": 6559,
        "embed": false,
        "format": "hls",
        "is_live": false,
        "drm": false,
        "drm_type": null,
        "license_type": null,
        "spritesheets": [

No DRM in either

**Comment by IceFreak66** [comment] 2024-03-13 10:25
You can try it yourself : 
https://k7.ftven.fr/videos/8f807d3c-d474-4957-8f7c-6c7bcd2983ee?country_code=FR&w=829&h=466&screen_w=1920&screen_h=1080&player_version=5.106.0&domain=www.france.tv&device_type=desktop&browser=safari&browser_version=122&os=ios&gmt=%2B0100&video_product_id=5692284

just play around with the os and browser parameters

**Comment by joaopa00** [comment] 2024-03-13 10:26
And no I can't play by myself. I am geoblocked for several months....

**Comment by Barthorel** [comment] 2024-03-24 14:59
> Hello, thank you IceFreak66 for your file. Now a gift for easy use (stick and nvidiashiel...). I've modified addon and put in new resolver. Cadeau pour vous les gars fichier a ajouter dans kodi [plugin.video.catchuptvandmore-0.2.40~b1_modf2.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14468617/plugin.video.catchuptvandmore-0.2.40.b1_modf2.zip)
> 
> France TV marche a nouveau. All work perfectly..

Hello, i'm new here and try to install the "@Olivier1967's gift" on myfirestick  but Idk how to do that with Kodi.
 I think I don't use the good method. Is there a tuto to help me or something?

**Comment by JazzyEADG** [comment] 2024-03-26 23:18
@Barthorel   I don't have this kind of asset but you can try a ftp connection I guess

**Comment by enigma131** [comment] 2024-03-29 13:01
Renaming and replacing resolver_proxy.py.txt in folder solve the problem for France TV except for France 5 (for it  I have an infinite search). Thanks for the hard work ;)

**Comment by pols12** [comment] 2024-03-30 20:25
## Fire Stick
> try to install the "Olivier1967's gift" on myfirestick but Idk how to do that with Kodi.

A general guideline is to avoid ugly and disrespectful Amazon products and services. However, I tried to get information from the web to provide those methods, hoping they can help you.

### Method 1: From a command line interface shell
1.  Connect to an ADB shell https://developer.amazon.com/docs/fire-tv/connecting-adb-to-device.html
You may use ADBLink for convenience.
2. 
       wget https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14466635/resolver_proxy.py.txt
       adb shell mv /sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py /sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py.bkp
       adb push resolver_proxy.py.txt /sdcard/Download
       adb shell mv /sdcard/Download/resolver_proxy.py.txt /sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py

I’m not sure about locations (/sdcard …). You can probably get current location thanks to `adb shell pwd`, and browse file system thanks to `adb shell ls` and `adb shell cd` to find `data/org.wbmc.kodi` directory.

### Method 2: From Fire OS apps
1. Download the patch (e.g. from Downloader or ES File Explorer)
2. Rename/Remove origin `Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py` (e.g. to resolver_proxy.py.bkp. You can use ES File Explorer)
3. Move the downloaded patch to `Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/` and rename it to `resolver_proxy.py`


### Method 3: From Fire OS, then Kodi
1. Download zip file from Fire Stick (e.g. using Downloader): https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14468617/plugin.video.catchuptvandmore-0.2.40.b1_modf2.zip
2. Ensure unknown sources are allowed: Settings>System>Add-ons>Unknown Sources
4. Add-ons>Install from zip file. Find and select the downloaded `plugin.video.catchuptvandmore-0.2.40.b1_modf2.zip
` file; then install it.

**Comment by darkb1967** [comment] 2024-04-03 07:55
Hello, an official patch is out i think : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1299
It's working for me.

**Comment by jeff2900** [comment] 2024-04-05 10:11
To fix "Download failed with error 403" when playing dash streams in francetv replays, you must modify the header provided to the inputstream.adaptive addon.
```
kodi.log
...
2024-04-05 09:41:47.646 T:10700   error <general>: AddOnLog: inputstream.adaptive: Download failed with error 403: https://cloudreplay.ftven.fr/ZXhwPTE....
```
Fix tested with kodi 20 et kodi 21:
```
resolver_proxy.py
476:    params = {
477:        'country_code': geoip_value,
478:        'domain': 'www.france.tv',
479:        'device_type': 'desktop',
480:        'browser': 'chrome',
481:    }
...
557:            item.path = location_url
558:            item.property['inputstream.adaptive.stream_headers'] = stream_headers
558:            item.property['inputstream.adaptive.manifest_headers'] = stream_headers

```
[resolver_proxy.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14883436/resolver_proxy.txt)

**Comment by sebmourlhou** [comment] 2024-04-18 06:59
It works with the last version 0.2.40~beta03

**Comment by jeff2900** [comment] 2024-04-18 13:14
Sorry France.tv replay don't work for me under kodi 21, always error 403.

Fix by changing in file resolver_proxy.py line 
241:    if get_kodi_version() == 20:
By
241:    if get_kodi_version() >= 20

**Closed as completed** 2024-04-18 21:52 UTC
