### ISSUE TITLE
swiss channel RTS Un not working 

### ISSUE THREAD

**Issue by Che-debarras** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#438] opened 2021-02-17 17:26 UTC
### Describe the bug
The folders of the swiss channels cannot be opened.
I tried to open the folder SERIES from RTS but it is impossible
I cleaned the cache even reinstall but the bug is still here

NB: La Deux , La Trois and TIPIK are not working in Belgium Channels

### To Reproduce
Just click SUISSE/RTS/SERIES to see if it opens

**Comment by wwark** [comment] 2021-02-17 21:25
Thanks @Che-debarras 
I reproduce the issue.
I will take a look tomorrow.

**Comment by wwark** [comment] 2021-02-20 08:46
Hi @Che-debarras,

A first fix is present on the last beta 0.2.31~beta02.
Some title are Unkown  (need works for what) and also SWISSINFO needs some work.

If you find another thing do not hesitate to give feedback.

Thanks,

**Comment by Che-debarras** [comment] 2021-02-20 08:52
I use this beta and it still doesn't work it says " cette ressource n'est pas disponible" httperror code 404.

**Comment by Che-debarras** [comment] 2021-02-20 08:52
I use this beta and it still doesn't work it says " cette ressource n'est pas disponible" httperror code 404.

**Comment by wwark** [comment] 2021-02-20 08:59
Are you using the beta 0.2.31~beta02 just release ?

**Comment by Che-debarras** [comment] 2021-02-20 09:02
No it is not in kodi yet

**Comment by wwark** [comment] 2021-02-20 09:32
Thanks !
I will check for the next page and add more infos for contents.
Live TV is working great on my side and I didn't touch this part. What is the error you get in the log ?

**Comment by Che-debarras** [comment] 2021-02-20 09:59
@wwark 
There is no error message , the channel doesn't display any image,  when we click the channel, there is the round symbol turns endlessly without displaying image.

Others channels are working fine but not RTS Un.

**Comment by wwark** [comment] 2021-02-20 12:03
It is the same code for other RTS live TV ... If you tried time to time is it working ?

I have fixed some other issued on 0.2.31~beta03 but the UNKNOWN titles remains still work todo.
(duration, date, SWISSINFO, next page are done)

**Comment by Che-debarras** [comment] 2021-02-20 12:09
All RTS Channels are working (RTS Deux, RTS Info, RTS Couleur3) and Rouge TV is also working.
Only RTS Un is not working and doesn't give any message error.

See picture

**Comment by wwark** [comment] 2021-02-20 12:50
Yes it might happens. The Kodi player could froze for that it depends of the live stream, the device, the connection, the drm lib used ...
THanks,

**Comment by Che-debarras** [comment] 2021-02-20 14:12
> Yes it might happens. The Kodi player could froze for that it depends of the live stream, the device, the connection, the drm lib used ...
> THanks,

It doesn't make sense, if all RTS Channels why RTS Un doesn't work?

**Comment by wwark** [comment] 2021-02-20 15:06
The kodi player starts the stream like you show on your screenshot. The plugin done his part of the job to provide information to Kodi Player to play the stream.
It freeze on the Kodi Player in your case.
So the log in debug level may help to understand the issue. The cause could be the one I have already listed in my previous comment.

**Comment by Che-debarras** [comment] 2021-02-20 15:45
Don't be angry because of a bug from your addon.
The plugin doesn't do all its part. The issue here is from the plugin 
I don't criticize but don't accuse Kodi because you can't fix it.
I told you : I have a High speed internet with fibre
All video from sd to 4k are played smoothly from video plugins I use
In your plugins, RTS are played good enough except one RTS Un.

You can't throw the fault to kodi who does it job to play all kind of video smoothly at High résolution from many plugins excepted yours I mean at least a small part  of your plugin.

there is probably something missing in your plugin to handle the live tv streaming because believe me or not, Kodi play very well live tv in High resolution.

Anyway thank you for your help but please stop being in a defense position each time you can't fix a bug.

Have a nice weekend

**Comment by wwark** [comment] 2021-02-20 16:16
I'm not angry but I like take your time :+1: 
I proposed help to check the log in debug mode.
Without it, it will be difficult to help you more.

**Comment by Che-debarras** [comment] 2021-02-20 20:08
> I'm not angry but I like take your time 👍
> I proposed help to check the log in debug mode.
> Without it, it will be difficult to help you more.

You don't take my time , I kindly give you my time , we are the weekend, I have plenty of time.
I will check the log but if you reproduce the issue you can have the log yourself.
Like I said you can't take my time to have log , I give my time when i want 👍😉

I am just kidding , 😌

**Comment by wwark** [comment] 2021-03-14 10:35
Hi,
Is the issue still remains on your side ?
Could you please provide the log ? If it is not the case, we will close this ticket in the next few days.
Thanks,

**Comment by Che-debarras** [comment] 2021-03-14 10:50
> Hi,
> Is the issue still remains on your side ?
> Could you please provide the log ? If it is not the case, we will close this ticket in the next few days.
> Thanks,

Give me time to test the channels from belgium but the same issue appears with canadian channels

**Comment by wwark** [comment] 2021-03-14 11:11
Ok if the issue is not present anymore.
I will close this ticket because no change between 0.2.33neta05 and 0.2.34beta1 for RTS One.
Please be free to open a new ticket for this new issue, i will check also on my side.
Thanks for your return.

**Closed by wwark** 2021-03-14 11:11 UTC
Labels: Type: Bug
