### ISSUE TITLE
Add-On error not displaying channels

### ISSUE THREAD

**Issue by flof08** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#103] opened 2018-11-28 09:59 UTC
Hi,

First of all, thank you for this add-on.
It's been awesomely stable and used so far.

But since some days, it seems to have a bug. (I've seen last update is from 27th Nov., maybe related?)

I attached the log here also:
[kodi_18-11-28_07-28-51.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/2623835/kodi_18-11-28_07-28-51.log)

The Add-on is running on a raspi2, with Libreelec 8.2.5 => Kodi 17

The error itself does not seem to be very specific...
ERROR: plugin.video.catchuptvandmore [v.0.1.17]: Unhandled exception detected!

Any idea?

Thanks in advance!
Florian

**Comment by SylvainCecchetto** [comment] 2018-11-28 10:14
Hi flof08,

Thank you for your message and for this bug report, we will look at that ;-)

If you want you can use the "beta" version of the plugin in order to see if the bug is still present.
To do that you have to install the beta repo add-on of Krypton (catchuptvandmore.kodi.krypton.beta.zip) by following the wiki https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/wiki/Add-the-official-repository

Thank you!

**Comment by wwark** [comment] 2018-11-28 10:33
Hi @All,

I did some digging the error is during the parsing of xmltv_fr.xml.
@SylvainCecchetto the url https://repo.cecchettosylvain.fr/xmltv/xmltv_fr.xml return 404.

@flof08 can you please check if the file xmltv_fr.xml present in this PATH/addons/plugin.catchuptvandmore/ ? The file is maybe malformatted. what is his size? Can you please try to remove it and test again?

The PATH depends of the OS. You can find it at this url https://kodi.wiki/view/Userdata#Location_of_the_userdata_folder

Thanks,
Wwark

**Comment by wwark** [comment] 2018-11-28 10:44
Reproduce also on my side. The file xmltv_fr.xml contains the return HTTP 404 in html format.
The parsing failed because it is not xml format.
I will work for a hotfix for the version 0.1.x of the plugin in the case the file is not well formatted
Thanks,
Wwark.

**Comment by SylvainCecchetto** [comment] 2018-11-28 10:47
Sorry wwark, my bad, I removed xmltv_fr.xml -_-'

It should be good now. Thank you ;)

By the way, from the 0.2.0 version of the plugin, the xmltv_fr.xml file from my server will no longer be necessary. The guide information will be directly downloading and parsing on the user side.

**Comment by flof08** [comment] 2018-11-28 10:47
@wwark, I was just about to post the same conclusion!
Means also that in the error is still present in the beta repo?

**Comment by SylvainCecchetto** [comment] 2018-11-28 10:49
Yes you can delete the xml file from your userdata folder and restart the plugin in order to download it again. It should work ...

**Comment by flof08** [comment] 2018-11-28 11:16
Ok, done that.

Rebooted the Pi, launched the add-on, it worked.
Thanks guys!

**Comment by wwark** [comment] 2018-11-28 11:55
Thank you for the fix ! and the tests.
@SylvainCecchetto in the hotfix for 0.1.x we can add a try/catch during the parsing what do you think and push a new version 0.1.18.

Wwark

**Comment by flof08** [comment] 2018-11-28 13:04
> Yes something like that would be good. I don't know if a function to check the validity of an XML exists? Maybe the try/catch is the only way ;-)

An xml parser can throw an exception if parsing returns an error (see [link](http://code.activestate.com/recipes/52256-check-xml-well-formedness/))

**Comment by wwark** [comment] 2018-11-28 17:57
Thank you Florent and Sylvain !
I push the hotfix 0.1.18.
I closed this ticket.

**Closed by wwark** 2018-11-28 17:57 UTC
Labels: Guide TV, Version 0.1.x
