### ISSUE TITLE
M6 channel not working anymore

### ISSUE THREAD

**Issue by guilders** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#697] opened 2022-03-15 16:17 UTC
### Describe the bug
An error message appears when trying to watch M6

### To Reproduce
launch M6 channel

### Screenshots
<a href="https://ibb.co/nCbLW1g"><img src="https://i.ibb.co/SrP3Lms/Capture.jpg" alt="Capture" border="0"></a>

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 18.9 (libreelec)
 - Catch-up TV & More version: latest beta
 - Installation method: official depository

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by darodi** [comment] 2022-03-15 16:24
not a CUTVM problem but a librelec problem.

Duplicate of #695
Duplicate of #685 

You should try that:

https://forum.libreelec.tv/thread/24898-error-with-plexkodiconnect/


> Well after some research i installed the Locale addon in the libreelec repository and the errors disapear..
> I hope everything goes fine from now on ;)

**Comment by joaopa00** [comment] 2022-03-15 19:02
Duplicate

**Closed by joaopa00** 2022-03-15 19:02 UTC

**Comment by guilders** [comment] 2022-03-16 07:29
> not a CUTVM problem but a librelec problem.
> 
> Duplicate of #695 Duplicate of #685
> 
> You should try that:
> 
> https://forum.libreelec.tv/thread/24898-error-with-plexkodiconnect/
> 
> > Well after some research i installed the Locale addon in the libreelec repository and the errors disapear..
> > I hope everything goes fine from now on ;)

Problem solved with that solution, many thanks for your help.
