### ISSUE TITLE
Home Channel Live

### ISSUE THREAD

**Issue by jcorsaut** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#232] opened 2019-10-29 02:47 UTC
Live version of home channel is giving an error when selected.   Error is 'index error, list out of range'.

**Comment by SylvainCecchetto** [comment] 2019-10-29 06:50
I will try to have a look today. 
Thank you for the issue. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SylvainCecchetto** [comment] 2019-10-29 07:15
@wwark, I find the bug but I don't know how to resolve it, sure you know better than me UTKTVplay channels.

The issue is here https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/8957e18a6077ae6d8bffbbf29cfe4695f2cfbb33/resources/lib/channels/uk/uktvplay.py#L396-L398

`respdatachannel` should contains the string `data-channel` but I can't find it in respdatachannel.text.
I attach to this issue a text file containing the string that I obtain in `respdatachannel.text`.

If you can have a look at a moment ;-)

[respdatachannel.text.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/3782104/respdatachannel.txt)

**Comment by wwark** [comment] 2019-11-03 04:13
Hi,
Sorry Really and Home are not available anymore on the website of uktvplay.
https://uktvplay.uktv.co.uk/channel
We will remove them from this plugin.
Regards,
Wwark

**Comment by wwark** [comment] 2019-11-11 06:50
Close this issue.

**Closed by wwark** 2019-11-11 06:50 UTC
Labels: Content no more available
